.github/workflows/backend.yml
This PR adds a cicd pipeline for the backend.
It will change to accomodate new code change.
It took a few minutes to do
=> Add support for the cicd

.github/workflows/backend.yml
This pr adds the emulator for local testing
=> Feature cicd golang

backend/Dockerfile, docker-compose.yml, frontend/Dockerfile, frontend/server-config-prod/default.conf
This PR adds the necessary files for the deployment
=> Feature deploy front back

frontend/src/app/title/title.component.html
Just a PR to test auto deployment
=> test auto deployment

backend/Dockerfile, docker-compose.yml
This PR fix the problem we had in production due to the secret not beeing injected in the docker container.
=> Fix the secret path in dockerfile

backend/api/api.go, backend/api/api_test.go, backend/db/db.go, backend/db/db_test.go
This function refactor the workflow for register & login
It use the new user struct as defined in the json
=> Refactor user creation

backend/api/api.go, backend/api/api_test.go, backend/db/db.go, backend/db/db_test.go
=> Feature backend listsocks

backend/api/api.go
This PR add the cors header to the response
@superjeffcplusplus
=> Add the cors header

backend/api/api.go, backend/api/api_test.go, backend/db/db.go, backend/db/db_test.go
=> Implements user informations

backend/api/api.go, backend/db/db.go, backend/db/db_test.go
This pr implement said endpoint.
Close #38
=> implement the /sock/:sockID endpoint

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/authentication-button/authentication-button.component.html, frontend/src/app/authentication-button/authentication-button.component.scss, frontend/src/app/authentication-button/authentication-button.component.spec.ts, frontend/src/app/authentication-button/authentication-button.component.ts, frontend/src/app/dataModel/interface/link.model.ts, frontend/src/app/home-page/home-page.component.html, frontend/src/app/home-page/home-page.component.scss, frontend/src/app/home-page/home-page.component.ts, frontend/src/app/services/authService/access-control.service.ts, frontend/src/app/services/authService/auth.service.spec.ts, frontend/src/app/services/authService/auth.service.ts, frontend/src/app/services/authService/token-service.service.spec.ts, frontend/src/app/services/authService/token-service.service.ts, frontend/src/styles.scss
=> Feat frontend : logout

backend/api/api.go, backend/api/api_test.go, backend/db/db.go, backend/utils/array.go
=> Implements `PATCH /sock/:sockId`

frontend/package-lock.json, frontend/package.json, frontend/src/app/add-sock-page/add-sock-page.component (conflicted copy 2022-09-02 113243).scss, frontend/src/app/add-sock-page/add-sock-page.component.html, frontend/src/app/add-sock-page/add-sock-page.component.scss, frontend/src/app/add-sock-page/add-sock-page.component.spec.ts, frontend/src/app/add-sock-page/add-sock-page.component.ts, frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/styles.scss
We can now register a new sock
=> Frontend : add the new page add-sock

frontend/src/app/app.module.ts
A duplicated import make the build crash
=> Frontend hot fix

backend/api/api.go, backend/api/api_test.go, backend/db/db.go
=> Add a MatchResult field to Socks

backend/api/api.go, backend/api/api_test.go
* Add 307 temporary redirection for trailing slash
* Add a 404 handler using cors and message
* Add the no method handler
close #76
=> Add 404 handling and routing config

frontend/src/app/dataModel/sock.model.ts, frontend/src/app/forms/add-sock-form/add-sock-form.component.html, frontend/src/app/forms/add-sock-form/add-sock-form.component.spec.ts, frontend/src/app/forms/add-sock-form/add-sock-form.component.ts, frontend/src/app/login-page/login-page.component.ts, frontend/src/app/services/http-interceptors/auth-interceptor.service.ts
We can now register a new sock in the database.
=> Frontend: "add sock form" submit

frontend/src/app/services/backendservice/backend-link.service.ts, frontend/src/app/services/index.ts, frontend/src/app/services/socks-manager.service.spec.ts, frontend/src/app/services/socks-manager.service.ts, frontend/src/app/services/socksManager/socks-manager.service.spec.ts, frontend/src/app/services/socksManager/socks-manager.service.ts
This feature this feature will make it easier to handle socks.
=> Frontend : add SocksService

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/match-lose/match-lose.component.html, frontend/src/app/match-lose/match-lose.component.scss, frontend/src/app/match-lose/match-lose.component.spec.ts, frontend/src/app/match-lose/match-lose.component.ts, frontend/src/app/match-win/match-win.component.html, frontend/src/app/match-win/match-win.component.scss, frontend/src/app/match-win/match-win.component.spec.ts, frontend/src/app/match-win/match-win.component.ts
Overview before the refactoring.
=> Frontend : win & lose page

backend/api/api.go, backend/db/db.go
This PR add the same check on the form sent by the user as the register function.
Before that a user could update his profile with all field empty. Now it is forbiden
=> Added same check as registration for update profile

backend/README.md
This PR add a README.md file in the backend folder explaining how to build and configure the backend
=> Add instruction for setup

frontend/angular.json
this PR increase the budget for the front. We encountered an issue where the final bundle was too big
close #101
=> Increase budget limit

backend/api/api.go
Like the title said, we saw that we have cors pb.
This should solve it
=> Add CORS to PATCH verbe

frontend/src/app/forms/login-form/login-form.component.ts, frontend/src/app/forms/signup-form/signup-form.component.ts, frontend/src/app/pages/matching-socks/proposed-sock/proposed-sock.component.ts, frontend/src/app/services/userService/user-service.service.ts
Bug in UserService caused a global crash.
=> Frontend: redirect after add sock success and fix UserService

backend/api/api.go, backend/api/api_test.go, backend/db/cache.go, backend/db/db.go, backend/db/db_test.go
This adds a caching system for the recommendation algorithm
=> Implemented caching for the database

frontend/src/app/pages/matching-socks/matching-socks.component.ts, frontend/src/app/pages/matching-socks/proposed-sock/proposed-sock.component.html, frontend/src/app/pages/matching-socks/proposed-sock/proposed-sock.component.ts, frontend/src/app/services/socksManager/socks-manager.service.ts
The server-side cache was deemed sufficient.
I took the opportunity to do some cleaning
=> Frontend: remove local cache for socks

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/arrow-down/arrow-down.component.html, frontend/src/app/arrow-down/arrow-down.component.scss, frontend/src/app/arrow-down/arrow-down.component.spec.ts, frontend/src/app/arrow-down/arrow-down.component.ts, frontend/src/app/backbutton/backbutton.component.html, frontend/src/app/backbutton/backbutton.component.scss, frontend/src/app/pages/add-sock-page/add-sock-page.component.html, frontend/src/app/pages/add-sock-page/add-sock-page.component.ts, frontend/src/app/pages/matching-socks/matching-socks.component.html, frontend/src/app/pages/my-account/my-account.component.html, frontend/src/app/pages/my-account/my-account.component.ts, frontend/src/app/pages/signup-page/signup-page.component.html, frontend/src/app/pages/signup-page/signup-page.component.scss, frontend/src/app/pages/signup-page/signup-page.component.ts, frontend/src/app/pages/sock-list/sock-list.component.html, frontend/src/styles.scss
- adds arrowdown wherever useful
- back button now in fixed position
=> Frontend: UX improvement
